// Tests for `src/codebase/model/id.rs`.
//
// The ids are newtypes over a string, generated by one macro. They are
// `#[serde(transparent)]`, which is the part worth pinning: these appear in
// Parquet and JSON that other tools read, and wrapping them in an object would
// be a silent format change rather than a compile error.
#![allow(clippy::unwrap_used, clippy::expect_used)]
use entl::codebase::{ArtifactId, EcosystemId, LanguageId, PackageId};

#[test]
fn an_id_keeps_the_string_it_was_made_from() {
    assert_eq!(LanguageId::new("rust").as_str(), "rust");
    assert_eq!(PackageId::from("owner/name").as_str(), "owner/name");
}

#[test]
fn ids_serialise_as_the_bare_string() {
    let json = serde_json::to_string(&EcosystemId::new("cargo")).unwrap();
    assert_eq!(json, "\"cargo\"");
    let back: EcosystemId = serde_json::from_str("\"cargo\"").unwrap();
    assert_eq!(back.as_str(), "cargo");
}

/// Ordering is the string's, which is what lets a sorted list of ids be
/// searched by `&str` without materialising an id to compare against.
#[test]
fn ids_order_as_their_strings_do() {
    let mut ids = [
        ArtifactId::new("b"),
        ArtifactId::new("a"),
        ArtifactId::new("c"),
    ];
    ids.sort();
    assert_eq!(
        ids.iter().map(ArtifactId::as_str).collect::<Vec<_>>(),
        ["a", "b", "c"]
    );
}
