//! Renders the checked-in table and the human-readable report.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::corpus::{Samples, Source};
use crate::stats::{self, Metric, Pair};

pub struct Report<'a> {
    pub source: Source,
    pub revision: &'a str,
    pub tasks: usize,
    pub baseline: &'a str,
    pub samples: &'a BTreeMap<&'static str, Samples>,
    pub pairs: &'a [Pair],
    pub bytes: &'a BTreeMap<&'static str, f64>,
    pub lines: &'a BTreeMap<&'static str, f64>,
    pub core: &'a [&'static str],
    pub panel: usize,
    pub balanced: &'a BTreeMap<&'static str, f64>,
    pub minimum_shared_tasks: u32,
    pub minimum_language_tasks: usize,
}

impl Report<'_> {
    fn languages(&self) -> Vec<&'static str> {
        stats::languages_in(self.pairs)
    }

    /// The largest fractional gap between a language's fitted index ratio and a
    /// ratio measured directly against one other language.
    fn deviation(&self, language: &str) -> f64 {
        self.pairs
            .iter()
            .filter(|pair| pair.left == language || pair.right == language)
            .map(|pair| (stats::residual(pair, Metric::Bytes, self.bytes).exp() - 1.0).abs())
            .fold(0.0, f64::max)
    }
}

pub fn table(report: &Report) -> String {
    let mut output = String::new();
    output.push_str(&header(report));
    let _ = write!(
        output,
        r#"
/// The corpus the measurements were taken from.
pub const VERBOSITY_CORPUS: &str = "{corpus}";

/// The corpus revision the checked-in numbers were measured at.
pub const VERBOSITY_CORPUS_REVISION: &str = "{revision}";

/// The language every index is expressed relative to.
pub const VERBOSITY_BASELINE: &str = "{baseline}";
"#,
        corpus = report.source.home(),
        revision = report.revision,
        baseline = report.baseline,
    );
    output.push_str(TYPES);

    let _ = write!(
        output,
        "\nstatic VERBOSITY: &[(&str, LanguageVerbosity)] = &[\n"
    );
    for language in report.languages() {
        let _ = write!(
            output,
            "    (\n        {language:?},\n        LanguageVerbosity {{\n            bytes: {bytes:.4},\n            lines: {lines:.4},\n            tasks: {tasks},\n            deviation: {deviation:.4},\n        }},\n    ),\n",
            bytes = report.bytes[language],
            lines = report.lines[language],
            tasks = report.samples[language].len(),
            deviation = report.deviation(language),
        );
    }
    output.push_str("];\n");

    let _ = write!(
        output,
        "\nstatic RATIOS: &[(&str, &str, VerbosityRatio)] = &[\n"
    );
    for pair in report.pairs {
        let _ = write!(
            output,
            "    (\n        {left:?},\n        {right:?},\n        VerbosityRatio {{ bytes: {bytes:.4}, lines: {lines:.4}, tasks: {tasks} }},\n    ),\n",
            left = pair.left,
            right = pair.right,
            bytes = pair.bytes,
            lines = pair.lines,
            tasks = pair.tasks,
        );
    }
    output.push_str("];\n");
    output.push_str(LOOKUPS);
    output
}

fn header(report: &Report) -> String {
    format!(
        r#"// @generated by tools/verbosity. Do not edit by hand.
//! Relative source verbosity of the profiled languages.
//!
//! Every number here is a statistic derived from the {label} corpus: how much
//! program text each language needs for {unit}s that two languages both
//! implement, with comments and blank lines removed. That corpus is licensed
//! under the {license}. Entl does not redistribute it; only these measurements.
//!
//! Entl reports the measurement, not a verdict. {character} It is not a claim
//! about readability.
//!
//! It is also not a porting factor. This measures what a language needs when
//! someone writes a solution from the specification. Translating an existing
//! program into another language is a different quantity and can run the other
//! way: Bun's Zig-to-Rust rewrite expanded by about 1.37x in tokens, while
//! independently written Rust and Zig solutions put Rust at roughly 0.7x Zig.
//!
//! See `docs/verbosity-{id}.md` for the method, the full matrix, and how far a
//! single index per language falls short of explaining the pairs it came from.
"#,
        label = report.source.label(),
        unit = report.source.unit(),
        license = report.source.license(),
        id = report.source.id(),
        character = report.source.character(),
    )
}

const TYPES: &str = r#"
/// How much source text a language needs, relative to [`VERBOSITY_BASELINE`].
///
/// A value of 2.0 means that on the tasks measured, this language took about
/// twice as much program text as the baseline.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LanguageVerbosity {
    /// Relative bytes of program text, ignoring indentation.
    pub bytes: f32,
    /// Relative count of lines that hold program text.
    pub lines: f32,
    /// Corpus tasks this language contributed.
    pub tasks: u32,
    /// The largest fractional gap between this language's index ratio and a
    /// ratio measured directly against one other language. A single index per
    /// language cannot reproduce every pair exactly; this is how far off it
    /// gets. Prefer [`verbosity_ratio`] when comparing two specific languages.
    pub deviation: f32,
}

/// A ratio measured directly between two languages, on the tasks both
/// implement. More accurate for that pair than dividing two indexes.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct VerbosityRatio {
    /// Bytes of program text in the left language per byte in the right.
    pub bytes: f32,
    /// Lines in the left language per line in the right.
    pub lines: f32,
    /// Tasks both languages implement.
    pub tasks: u32,
}

impl VerbosityRatio {
    /// The same measurement with the languages swapped.
    pub fn inverted(&self) -> Self {
        Self { bytes: 1.0 / self.bytes, lines: 1.0 / self.lines, tasks: self.tasks }
    }
}
"#;

const LOOKUPS: &str = r#"
/// The verbosity of a language by profile ID, if the corpus covers it.
pub fn verbosity(language: &str) -> Option<&'static LanguageVerbosity> {
    VERBOSITY
        .binary_search_by_key(&language, |(id, _)| *id)
        .ok()
        .map(|index| &VERBOSITY[index].1)
}

/// The measured ratio of `left` to `right`, if the corpus covers both with
/// enough tasks in common.
pub fn verbosity_ratio(left: &str, right: &str) -> Option<VerbosityRatio> {
    if left == right {
        return None;
    }
    let (key, inverted) = if left < right { ((left, right), false) } else { ((right, left), true) };
    let found = RATIOS
        .binary_search_by_key(&key, |(left, right, _)| (*left, *right))
        .ok()
        .map(|index| RATIOS[index].2)?;
    Some(if inverted { found.inverted() } else { found })
}

/// Every measured pair, ordered and deduplicated: each pair appears once, with
/// the alphabetically first language on the left.
pub fn verbosity_ratios() -> impl Iterator<Item = (&'static str, &'static str, VerbosityRatio)> {
    RATIOS.iter().map(|(left, right, ratio)| (*left, *right, *ratio))
}
"#;

/// Title case for a corpus's unit noun, for table headings.
fn capitalize(word: &str) -> String {
    let mut characters = word.chars();
    match characters.next() {
        Some(first) => first.to_uppercase().collect::<String>() + characters.as_str(),
        None => String::new(),
    }
}

pub fn document(report: &Report) -> String {
    let languages = report.languages();
    let mut output = String::new();

    let _ = write!(
        output,
        r#"# Language verbosity

<!-- @generated by tools/verbosity. Do not edit by hand. -->

How much source text each profiled language needs for the same work, measured on
[{label}]({corpus}) at revision `{revision}`.

The corpus is licensed under the {license}. Entl redistributes no corpus source
either way: the tool reads a checkout the operator downloads, and only the
statistics on this page and in `crates/entl/src/codebase/profiles/verbosity.rs`
are checked in.

## Method

1. A solution is reduced to program text: comments are removed using the
   language's own `CommentSyntax` from its Entl profile, blank lines are
   dropped, and each remaining line is trimmed so indentation style does not
   read as verbosity. String literals are kept — they are program content.
2. {selection}
{comparison}

{corpus_line} Languages with no algorithmic presence in the corpus — HTML, CSS,
JSON, YAML, TOML, Markdown, Dockerfile, Vue, Svelte — carry no measurement at
all.

## Index

{index_blurb}

{index_columns}"#,
        selection = report.source.selection(),
        index_blurb = if report.source.has_spread() {
            format!(
                "Least-squares fit of one number per language against every measured pair,\nweighted by shared unit count and normalized so `{baseline}` is 1.0.\n`deviation` is the largest fractional gap between this index and a ratio\nmeasured directly against one other language.",
                baseline = report.baseline
            )
        } else {
            format!(
                "Every language is measured on the one shared unit and normalized so\n`{baseline}` is 1.0, so the index is that measurement rather than a fit over\nmany. No deviation column is shown: with a single unit the ratios are exactly\ntransitive and every residual is zero by arithmetic, and there is no spread\nhere to put an error bar on.",
                baseline = report.baseline
            )
        },
        index_columns = if report.source.has_spread() {
            format!(
                "| Language | Bytes | Lines | {unit}s | Deviation |\n| --- | ---: | ---: | ---: | ---: |\n",
                unit = capitalize(report.source.unit())
            )
        } else {
            "| Language | Bytes | Lines |\n| --- | ---: | ---: |\n".to_owned()
        },
        comparison = if report.source.has_spread() {
            format!(
                "3. Two languages are compared **only on {unit}s both implement**, so every\n   ratio is a paired measurement. The ratio is the geometric mean of the\n   per-{unit} ratios.\n4. A pair needs at least {shared} shared {unit}s to be reported, and a language\n   needs at least {language} {unit}s to be included.",
                unit = report.source.unit(),
                shared = report.minimum_shared_tasks,
                language = report.minimum_language_tasks,
            )
        } else {
            "3. Every language implements the one unit, so each pair is compared directly\n   and there is nothing to average over.".to_owned()
        },
        corpus_line = if report.source.has_spread() {
            format!(
                "Corpus: {tasks} {unit}s, {languages} of Entl's language profiles cleared the floor.",
                tasks = report.tasks,
                unit = report.source.unit(),
                languages = languages.len(),
            )
        } else {
            format!(
                "Corpus: one {unit} per language, {languages} of Entl's language profiles.",
                unit = report.source.unit(),
                languages = languages.len(),
            )
        },
        corpus = report.source.home(),
        label = report.source.label(),
        license = report.source.license(),
        revision = report.revision,
    );

    let mut ranked = languages.clone();
    ranked.sort_by(|left, right| {
        report.bytes[left]
            .partial_cmp(&report.bytes[right])
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    for language in &ranked {
        let _ = writeln!(
            output,
            "{row}",
            row = if report.source.has_spread() {
                format!(
                    "| `{language}` | {bytes:.2} | {lines:.2} | {tasks} | {deviation:.0}% |",
                    bytes = report.bytes[language],
                    lines = report.lines[language],
                    tasks = report.samples[language].len(),
                    deviation = report.deviation(language) * 100.0,
                )
            } else {
                format!(
                    "| `{language}` | {bytes:.2} | {lines:.2} |",
                    bytes = report.bytes[language],
                    lines = report.lines[language],
                )
            },
        );
    }

    output.push_str("\n## Matrix\n\nBytes of program text in the row language per byte in the column language, measured directly on the tasks that pair shares. Prefer these to a quotient of two index values.\n\n");
    output.push_str(&matrix(report, &ranked, Metric::Bytes));

    output.push_str("\nShared task count per pair:\n\n");
    output.push_str(&counts(report, &ranked));

    if report.source.has_spread() {
        let _ = write!(
            output,
            r#"
    ## How far from transitive

    The matrix is not exactly transitive. C-to-Java need not equal
    (C-to-Python)(Python-to-Java), because each pair is averaged over a different
    slice of the corpus: the tasks C and Java both implement are not the tasks C and
    Python both implement, and the languages that turn up on hard tasks are not the
    ones that turn up on easy ones. The index above is the best single
    reconciliation of those pairs; the deviation column is what reconciling them
    cost.

    Which languages appear here is decided by Entl's language profiles, not by the
    corpus — the corpus covers hundreds more. Adding a profile with comment syntax
    and a corpus mapping extends the matrix.

    The worst disagreements, composing two measured ratios against the third
    measured directly:

    | Path | Composed | Direct | Gap | Thinnest leg |
    | --- | ---: | ---: | ---: | ---: |
    "#
        );
        for triangle in stats::triangles(report.pairs, Metric::Bytes)
            .iter()
            .take(10)
        {
            let [left, middle, right] = triangle.through;
            let _ = writeln!(
                output,
                "| `{left}`→`{middle}`→`{right}` | {composed:.3} | {direct:.3} | {gap:+.0}% | {legs} tasks |",
                composed = triangle.composed,
                direct = triangle.direct,
                gap = (triangle.composed / triangle.direct - 1.0) * 100.0,
                legs = triangle.tasks.iter().copied().min().unwrap_or_default(),
            );
        }

        let _ = write!(
            output,
            r#"
    ### Balanced panel

    Restricting to the {panel} tasks that all {core} well-covered languages
    implement makes the ratios transitive by construction, since every language is
    then averaged over an identical set of tasks. The gap between that index and the
    all-pairs index above is the part of the disagreement that comes from task
    selection rather than from the languages.

    The gap leans one way. Tasks that every language implements are the short,
    popular ones, where a fixed cost — includes, a class, a `main` — is a larger
    share of the whole. Measured only there, every language looks closer to the
    baseline than the full corpus says it is.

    | Language | All pairs | Balanced panel | Gap |
    | --- | ---: | ---: | ---: |
    "#,
            panel = report.panel,
            core = report.core.len(),
        );
        let mut balanced = report.core.to_vec();
        balanced.sort_by(|left, right| {
            report.balanced[left]
                .partial_cmp(&report.balanced[right])
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        for language in &balanced {
            let all = report.bytes[language];
            let panel = report.balanced[language];
            let _ = writeln!(
                output,
                "| `{language}` | {all:.2} | {panel:.2} | {gap:+.0}% |",
                gap = (panel / all - 1.0) * 100.0,
            );
        }
    } else {
        output.push_str(
            r#"
## How far from transitive

Not at all, and that is arithmetic rather than a result. Every pair is derived
from the same sixteen measurements, so composing two ratios reproduces the third
exactly and the least-squares fit has nothing to reconcile. The transitivity
check and the balanced panel that the collection corpora report are omitted
here: with one shared unit they would be measuring the identity.

What this corpus cannot tell you is how much of its disagreement with the
others is size and how much is genre. One program is one genre, and this one is
an interpreter — tagged unions, recursion, and manual memory management for a
garbage-collected target. Separating the two would take several mid-sized
programs implemented in the same set of languages.
"#,
        );
    }

    output.push_str(
        r#"
## What this does not measure

The corpus is small, self-contained tasks. That rewards a terse standard library
and charges any language that requires declarations, imports, or a class to hold
`main` — real costs, but ones that amortize away in a large program and so
overstate the gap at scale.

Solutions are contributed, not controlled, and they do not all answer the same
question. Ackermann in C ships the function plus a `main` that prints a table;
Ackermann in Ruby ships the function. Both are valid entries; only one includes
a driver. Taking the median across a task's solutions damps this, but it does
not remove it, and it runs the same direction as the ceremony it is measured
alongside: the languages that need a `main` are the ones whose contributors
tend to write one.

Two more, smaller: the corpus files Kotlin solutions as scripts, which skip
ceremony a Kotlin application file carries; and languages near the task floor
(`typescript`, `zig`, `sql`) rest on few enough shared tasks that a handful of
entries moves them, which is what their deviation figures are reporting.

None of this is a statement about readability, maintainability, or how long a
task takes to write.
"#,
    );
    output
}

fn matrix(report: &Report, languages: &[&'static str], metric: Metric) -> String {
    grid(
        report,
        languages,
        |pair, transposed| {
            let ratio = stats::ratio(pair, metric);
            format!("{:.2}", if transposed { 1.0 / ratio } else { ratio })
        },
        |_| "1.00".to_owned(),
    )
}

fn counts(report: &Report, languages: &[&'static str]) -> String {
    grid(
        report,
        languages,
        |pair, _| pair.tasks.to_string(),
        |language| report.samples[language].len().to_string(),
    )
}

fn grid(
    report: &Report,
    languages: &[&'static str],
    cell: impl Fn(&Pair, bool) -> String,
    diagonal: impl Fn(&'static str) -> String,
) -> String {
    let lookup = report
        .pairs
        .iter()
        .map(|pair| ((pair.left, pair.right), pair))
        .collect::<BTreeMap<_, _>>();
    let mut output = String::new();

    let _ = write!(output, "| |");
    for language in languages {
        let _ = write!(output, " `{language}` |");
    }
    let _ = write!(output, "\n| --- |");
    for _ in languages {
        let _ = write!(output, " ---: |");
    }
    output.push('\n');

    for row in languages {
        let _ = write!(output, "| **`{row}`** |");
        for column in languages {
            let rendered = if row == column {
                diagonal(row)
            } else if let Some(pair) = lookup.get(&(*row, *column)) {
                cell(pair, false)
            } else if let Some(pair) = lookup.get(&(*column, *row)) {
                // Rendering the transpose keeps the grid symmetric without
                // storing both directions.
                cell(pair, true)
            } else {
                "–".to_owned()
            };
            let _ = write!(output, " {rendered} |");
        }
        output.push('\n');
    }
    output
}
