// @generated by tools/rosetta-verbosity. Do not edit by hand.
//! Relative source verbosity of the profiled languages.
//!
//! Every number here is a statistic derived from the Rosetta Code corpus: how
//! much program text each language needs for tasks that two languages both
//! implement, with comments and blank lines removed. Rosetta Code's own content
//! is licensed under the GNU Free Documentation License 1.2 and is not
//! redistributed by Entl; only these measurements are.
//!
//! Entl reports the measurement, not a verdict. Verbosity is source size on a
//! corpus of small self-contained tasks, which rewards languages with terse
//! standard libraries and charges languages that require declarations, imports,
//! or a class to hold `main`. It is not a claim about readability, and it does
//! not extrapolate to large programs.
//!
//! See `docs/verbosity.md` for the method, the full matrix, and the extent to
//! which a single index per language fails to explain the pairs it came from.

/// The corpus the measurements were taken from.
pub const VERBOSITY_CORPUS: &str = "https://github.com/acmeism/RosettaCodeData";

/// The corpus revision the checked-in numbers were measured at.
pub const VERBOSITY_CORPUS_REVISION: &str = "1d475861d7141ef2fafff293d9339f56e4b0f5db";

/// The language every index is expressed relative to.
pub const VERBOSITY_BASELINE: &str = "c";

/// How much source text a language needs, relative to [`VERBOSITY_BASELINE`].
///
/// A value of 2.0 means that on the tasks measured, this language took about
/// twice as much program text as the baseline.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LanguageVerbosity {
    /// Relative bytes of program text, ignoring indentation.
    pub bytes: f32,
    /// Relative count of lines that hold program text.
    pub lines: f32,
    /// Corpus tasks this language contributed.
    pub tasks: u32,
    /// The largest fractional gap between this language's index ratio and a
    /// ratio measured directly against one other language. A single index per
    /// language cannot reproduce every pair exactly; this is how far off it
    /// gets. Prefer [`verbosity_ratio`] when comparing two specific languages.
    pub deviation: f32,
}

/// A ratio measured directly between two languages, on the tasks both
/// implement. More accurate for that pair than dividing two indexes.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct VerbosityRatio {
    /// Bytes of program text in the left language per byte in the right.
    pub bytes: f32,
    /// Lines in the left language per line in the right.
    pub lines: f32,
    /// Tasks both languages implement.
    pub tasks: u32,
}

impl VerbosityRatio {
    /// The same measurement with the languages swapped.
    pub fn inverted(&self) -> Self {
        Self {
            bytes: 1.0 / self.bytes,
            lines: 1.0 / self.lines,
            tasks: self.tasks,
        }
    }
}

static VERBOSITY: &[(&str, LanguageVerbosity)] = &[
    (
        "c",
        LanguageVerbosity {
            bytes: 1.0000,
            lines: 1.0000,
            tasks: 1311,
            deviation: 0.1225,
        },
    ),
    (
        "c-sharp",
        LanguageVerbosity {
            bytes: 0.9751,
            lines: 0.8669,
            tasks: 1071,
            deviation: 0.0731,
        },
    ),
    (
        "cpp",
        LanguageVerbosity {
            bytes: 1.0962,
            lines: 0.9480,
            tasks: 1462,
            deviation: 0.0720,
        },
    ),
    (
        "go",
        LanguageVerbosity {
            bytes: 0.8339,
            lines: 0.9852,
            tasks: 1598,
            deviation: 0.1183,
        },
    ),
    (
        "java",
        LanguageVerbosity {
            bytes: 1.0522,
            lines: 0.8008,
            tasks: 1628,
            deviation: 0.0782,
        },
    ),
    (
        "javascript",
        LanguageVerbosity {
            bytes: 0.7534,
            lines: 0.6681,
            tasks: 1080,
            deviation: 0.1158,
        },
    ),
    (
        "kotlin",
        LanguageVerbosity {
            bytes: 0.8814,
            lines: 0.7184,
            tasks: 1172,
            deviation: 0.0800,
        },
    ),
    (
        "php",
        LanguageVerbosity {
            bytes: 0.5775,
            lines: 0.5432,
            tasks: 496,
            deviation: 0.1379,
        },
    ),
    (
        "python",
        LanguageVerbosity {
            bytes: 0.6237,
            lines: 0.4991,
            tasks: 1654,
            deviation: 0.2620,
        },
    ),
    (
        "ruby",
        LanguageVerbosity {
            bytes: 0.3981,
            lines: 0.3396,
            tasks: 1228,
            deviation: 0.0382,
        },
    ),
    (
        "rust",
        LanguageVerbosity {
            bytes: 0.9227,
            lines: 0.8315,
            tasks: 1220,
            deviation: 0.0910,
        },
    ),
    (
        "scala",
        LanguageVerbosity {
            bytes: 0.7066,
            lines: 0.4476,
            tasks: 954,
            deviation: 0.1240,
        },
    ),
    (
        "shell",
        LanguageVerbosity {
            bytes: 0.4227,
            lines: 0.4450,
            tasks: 369,
            deviation: 0.1688,
        },
    ),
    (
        "sql",
        LanguageVerbosity {
            bytes: 0.6465,
            lines: 0.4713,
            tasks: 88,
            deviation: 0.1508,
        },
    ),
    (
        "swift",
        LanguageVerbosity {
            bytes: 0.7478,
            lines: 0.6474,
            tasks: 641,
            deviation: 0.1688,
        },
    ),
    (
        "typescript",
        LanguageVerbosity {
            bytes: 0.8028,
            lines: 0.6628,
            tasks: 62,
            deviation: 0.2944,
        },
    ),
    (
        "zig",
        LanguageVerbosity {
            bytes: 1.3867,
            lines: 1.0615,
            tasks: 327,
            deviation: 0.2944,
        },
    ),
];

static RATIOS: &[(&str, &str, VerbosityRatio)] = &[
    (
        "c",
        "c-sharp",
        VerbosityRatio {
            bytes: 1.0367,
            lines: 1.1702,
            tasks: 936,
        },
    ),
    (
        "c",
        "cpp",
        VerbosityRatio {
            bytes: 0.9006,
            lines: 1.0434,
            tasks: 1181,
        },
    ),
    (
        "c",
        "go",
        VerbosityRatio {
            bytes: 1.1865,
            lines: 1.0000,
            tasks: 1266,
        },
    ),
    (
        "c",
        "java",
        VerbosityRatio {
            bytes: 0.9129,
            lines: 1.1987,
            tasks: 1262,
        },
    ),
    (
        "c",
        "javascript",
        VerbosityRatio {
            bytes: 1.3202,
            lines: 1.4854,
            tasks: 893,
        },
    ),
    (
        "c",
        "kotlin",
        VerbosityRatio {
            bytes: 1.1165,
            lines: 1.3553,
            tasks: 1034,
        },
    ),
    (
        "c",
        "php",
        VerbosityRatio {
            bytes: 1.8868,
            lines: 2.0371,
            tasks: 467,
        },
    ),
    (
        "c",
        "python",
        VerbosityRatio {
            bytes: 1.5636,
            lines: 1.9526,
            tasks: 1281,
        },
    ),
    (
        "c",
        "ruby",
        VerbosityRatio {
            bytes: 2.5043,
            lines: 2.9836,
            tasks: 1089,
        },
    ),
    (
        "c",
        "rust",
        VerbosityRatio {
            bytes: 1.0883,
            lines: 1.2067,
            tasks: 1008,
        },
    ),
    (
        "c",
        "scala",
        VerbosityRatio {
            bytes: 1.4350,
            lines: 2.2594,
            tasks: 856,
        },
    ),
    (
        "c",
        "shell",
        VerbosityRatio {
            bytes: 2.6555,
            lines: 2.5400,
            tasks: 350,
        },
    ),
    (
        "c",
        "sql",
        VerbosityRatio {
            bytes: 1.6536,
            lines: 2.2684,
            tasks: 83,
        },
    ),
    (
        "c",
        "swift",
        VerbosityRatio {
            bytes: 1.3857,
            lines: 1.5687,
            tasks: 577,
        },
    ),
    (
        "c",
        "typescript",
        VerbosityRatio {
            bytes: 1.1885,
            lines: 1.5090,
            tasks: 56,
        },
    ),
    (
        "c",
        "zig",
        VerbosityRatio {
            bytes: 0.7391,
            lines: 0.9626,
            tasks: 248,
        },
    ),
    (
        "c-sharp",
        "cpp",
        VerbosityRatio {
            bytes: 0.9128,
            lines: 0.9309,
            tasks: 1009,
        },
    ),
    (
        "c-sharp",
        "go",
        VerbosityRatio {
            bytes: 1.1704,
            lines: 0.8802,
            tasks: 1051,
        },
    ),
    (
        "c-sharp",
        "java",
        VerbosityRatio {
            bytes: 0.9348,
            lines: 1.0738,
            tasks: 1057,
        },
    ),
    (
        "c-sharp",
        "javascript",
        VerbosityRatio {
            bytes: 1.2871,
            lines: 1.3081,
            tasks: 816,
        },
    ),
    (
        "c-sharp",
        "kotlin",
        VerbosityRatio {
            bytes: 1.0811,
            lines: 1.1762,
            tasks: 936,
        },
    ),
    (
        "c-sharp",
        "php",
        VerbosityRatio {
            bytes: 1.6467,
            lines: 1.5983,
            tasks: 455,
        },
    ),
    (
        "c-sharp",
        "python",
        VerbosityRatio {
            bytes: 1.5685,
            lines: 1.7352,
            tasks: 1056,
        },
    ),
    (
        "c-sharp",
        "ruby",
        VerbosityRatio {
            bytes: 2.4220,
            lines: 2.4585,
            tasks: 907,
        },
    ),
    (
        "c-sharp",
        "rust",
        VerbosityRatio {
            bytes: 1.0454,
            lines: 1.0382,
            tasks: 910,
        },
    ),
    (
        "c-sharp",
        "scala",
        VerbosityRatio {
            bytes: 1.3870,
            lines: 1.9512,
            tasks: 804,
        },
    ),
    (
        "c-sharp",
        "shell",
        VerbosityRatio {
            bytes: 2.3415,
            lines: 2.0434,
            tasks: 322,
        },
    ),
    (
        "c-sharp",
        "sql",
        VerbosityRatio {
            bytes: 1.5571,
            lines: 1.9342,
            tasks: 81,
        },
    ),
    (
        "c-sharp",
        "swift",
        VerbosityRatio {
            bytes: 1.3178,
            lines: 1.3749,
            tasks: 555,
        },
    ),
    (
        "c-sharp",
        "typescript",
        VerbosityRatio {
            bytes: 1.3034,
            lines: 1.4669,
            tasks: 50,
        },
    ),
    (
        "c-sharp",
        "zig",
        VerbosityRatio {
            bytes: 0.7232,
            lines: 0.8607,
            tasks: 265,
        },
    ),
    (
        "cpp",
        "go",
        VerbosityRatio {
            bytes: 1.3191,
            lines: 0.9609,
            tasks: 1384,
        },
    ),
    (
        "cpp",
        "java",
        VerbosityRatio {
            bytes: 1.0347,
            lines: 1.1764,
            tasks: 1447,
        },
    ),
    (
        "cpp",
        "javascript",
        VerbosityRatio {
            bytes: 1.4308,
            lines: 1.3855,
            tasks: 1001,
        },
    ),
    (
        "cpp",
        "kotlin",
        VerbosityRatio {
            bytes: 1.2413,
            lines: 1.3084,
            tasks: 1055,
        },
    ),
    (
        "cpp",
        "php",
        VerbosityRatio {
            bytes: 2.0099,
            lines: 1.8788,
            tasks: 464,
        },
    ),
    (
        "cpp",
        "python",
        VerbosityRatio {
            bytes: 1.7349,
            lines: 1.8618,
            tasks: 1428,
        },
    ),
    (
        "cpp",
        "ruby",
        VerbosityRatio {
            bytes: 2.8468,
            lines: 2.9753,
            tasks: 1118,
        },
    ),
    (
        "cpp",
        "rust",
        VerbosityRatio {
            bytes: 1.1961,
            lines: 1.1355,
            tasks: 1142,
        },
    ),
    (
        "cpp",
        "scala",
        VerbosityRatio {
            bytes: 1.5569,
            lines: 2.1138,
            tasks: 865,
        },
    ),
    (
        "cpp",
        "shell",
        VerbosityRatio {
            bytes: 2.5301,
            lines: 2.1426,
            tasks: 329,
        },
    ),
    (
        "cpp",
        "sql",
        VerbosityRatio {
            bytes: 1.6681,
            lines: 2.0221,
            tasks: 87,
        },
    ),
    (
        "cpp",
        "swift",
        VerbosityRatio {
            bytes: 1.4520,
            lines: 1.4408,
            tasks: 622,
        },
    ),
    (
        "cpp",
        "typescript",
        VerbosityRatio {
            bytes: 1.4637,
            lines: 1.5529,
            tasks: 61,
        },
    ),
    (
        "cpp",
        "zig",
        VerbosityRatio {
            bytes: 0.7645,
            lines: 0.8407,
            tasks: 315,
        },
    ),
    (
        "go",
        "java",
        VerbosityRatio {
            bytes: 0.7673,
            lines: 1.1981,
            tasks: 1513,
        },
    ),
    (
        "go",
        "javascript",
        VerbosityRatio {
            bytes: 1.0954,
            lines: 1.4406,
            tasks: 1045,
        },
    ),
    (
        "go",
        "kotlin",
        VerbosityRatio {
            bytes: 0.9474,
            lines: 1.3552,
            tasks: 1160,
        },
    ),
    (
        "go",
        "php",
        VerbosityRatio {
            bytes: 1.4735,
            lines: 1.8854,
            tasks: 493,
        },
    ),
    (
        "go",
        "python",
        VerbosityRatio {
            bytes: 1.3301,
            lines: 1.9462,
            tasks: 1534,
        },
    ),
    (
        "go",
        "ruby",
        VerbosityRatio {
            bytes: 2.1575,
            lines: 3.0530,
            tasks: 1199,
        },
    ),
    (
        "go",
        "rust",
        VerbosityRatio {
            bytes: 0.8925,
            lines: 1.1719,
            tasks: 1172,
        },
    ),
    (
        "go",
        "scala",
        VerbosityRatio {
            bytes: 1.1671,
            lines: 2.1600,
            tasks: 942,
        },
    ),
    (
        "go",
        "shell",
        VerbosityRatio {
            bytes: 2.2062,
            lines: 2.5158,
            tasks: 366,
        },
    ),
    (
        "go",
        "sql",
        VerbosityRatio {
            bytes: 1.2820,
            lines: 2.1157,
            tasks: 87,
        },
    ),
    (
        "go",
        "swift",
        VerbosityRatio {
            bytes: 1.0902,
            lines: 1.4755,
            tasks: 636,
        },
    ),
    (
        "go",
        "typescript",
        VerbosityRatio {
            bytes: 1.0769,
            lines: 1.5514,
            tasks: 62,
        },
    ),
    (
        "go",
        "zig",
        VerbosityRatio {
            bytes: 0.6231,
            lines: 0.9243,
            tasks: 312,
        },
    ),
    (
        "java",
        "javascript",
        VerbosityRatio {
            bytes: 1.3539,
            lines: 1.1541,
            tasks: 1054,
        },
    ),
    (
        "java",
        "kotlin",
        VerbosityRatio {
            bytes: 1.1779,
            lines: 1.1070,
            tasks: 1134,
        },
    ),
    (
        "java",
        "php",
        VerbosityRatio {
            bytes: 1.7416,
            lines: 1.4160,
            tasks: 486,
        },
    ),
    (
        "java",
        "python",
        VerbosityRatio {
            bytes: 1.7204,
            lines: 1.6112,
            tasks: 1582,
        },
    ),
    (
        "java",
        "ruby",
        VerbosityRatio {
            bytes: 2.7283,
            lines: 2.4866,
            tasks: 1191,
        },
    ),
    (
        "java",
        "rust",
        VerbosityRatio {
            bytes: 1.1279,
            lines: 0.9506,
            tasks: 1200,
        },
    ),
    (
        "java",
        "scala",
        VerbosityRatio {
            bytes: 1.4327,
            lines: 1.7302,
            tasks: 933,
        },
    ),
    (
        "java",
        "shell",
        VerbosityRatio {
            bytes: 2.5499,
            lines: 1.8113,
            tasks: 351,
        },
    ),
    (
        "java",
        "sql",
        VerbosityRatio {
            bytes: 1.5000,
            lines: 1.6075,
            tasks: 88,
        },
    ),
    (
        "java",
        "swift",
        VerbosityRatio {
            bytes: 1.3127,
            lines: 1.1585,
            tasks: 633,
        },
    ),
    (
        "java",
        "typescript",
        VerbosityRatio {
            bytes: 1.3397,
            lines: 1.2433,
            tasks: 62,
        },
    ),
    (
        "java",
        "zig",
        VerbosityRatio {
            bytes: 0.7369,
            lines: 0.7046,
            tasks: 325,
        },
    ),
    (
        "javascript",
        "kotlin",
        VerbosityRatio {
            bytes: 0.8594,
            lines: 0.9240,
            tasks: 871,
        },
    ),
    (
        "javascript",
        "php",
        VerbosityRatio {
            bytes: 1.1884,
            lines: 1.0954,
            tasks: 440,
        },
    ),
    (
        "javascript",
        "python",
        VerbosityRatio {
            bytes: 1.2150,
            lines: 1.3507,
            tasks: 1062,
        },
    ),
    (
        "javascript",
        "ruby",
        VerbosityRatio {
            bytes: 1.8886,
            lines: 1.9679,
            tasks: 865,
        },
    ),
    (
        "javascript",
        "rust",
        VerbosityRatio {
            bytes: 0.8316,
            lines: 0.8205,
            tasks: 914,
        },
    ),
    (
        "javascript",
        "scala",
        VerbosityRatio {
            bytes: 1.0582,
            lines: 1.4640,
            tasks: 737,
        },
    ),
    (
        "javascript",
        "shell",
        VerbosityRatio {
            bytes: 1.5760,
            lines: 1.2641,
            tasks: 313,
        },
    ),
    (
        "javascript",
        "sql",
        VerbosityRatio {
            bytes: 1.2233,
            lines: 1.5953,
            tasks: 85,
        },
    ),
    (
        "javascript",
        "swift",
        VerbosityRatio {
            bytes: 0.9870,
            lines: 1.0282,
            tasks: 540,
        },
    ),
    (
        "javascript",
        "typescript",
        VerbosityRatio {
            bytes: 0.8820,
            lines: 1.0039,
            tasks: 57,
        },
    ),
    (
        "javascript",
        "zig",
        VerbosityRatio {
            bytes: 0.5441,
            lines: 0.6304,
            tasks: 285,
        },
    ),
    (
        "kotlin",
        "php",
        VerbosityRatio {
            bytes: 1.5706,
            lines: 1.3348,
            tasks: 471,
        },
    ),
    (
        "kotlin",
        "python",
        VerbosityRatio {
            bytes: 1.4149,
            lines: 1.4748,
            tasks: 1146,
        },
    ),
    (
        "kotlin",
        "ruby",
        VerbosityRatio {
            bytes: 2.1295,
            lines: 1.9761,
            tasks: 997,
        },
    ),
    (
        "kotlin",
        "rust",
        VerbosityRatio {
            bytes: 0.9363,
            lines: 0.8516,
            tasks: 939,
        },
    ),
    (
        "kotlin",
        "scala",
        VerbosityRatio {
            bytes: 1.2330,
            lines: 1.5694,
            tasks: 884,
        },
    ),
    (
        "kotlin",
        "shell",
        VerbosityRatio {
            bytes: 2.2281,
            lines: 1.6871,
            tasks: 347,
        },
    ),
    (
        "kotlin",
        "sql",
        VerbosityRatio {
            bytes: 1.4080,
            lines: 1.5296,
            tasks: 84,
        },
    ),
    (
        "kotlin",
        "swift",
        VerbosityRatio {
            bytes: 1.1585,
            lines: 1.0815,
            tasks: 584,
        },
    ),
    (
        "kotlin",
        "typescript",
        VerbosityRatio {
            bytes: 1.0101,
            lines: 0.9074,
            tasks: 52,
        },
    ),
    (
        "kotlin",
        "zig",
        VerbosityRatio {
            bytes: 0.6165,
            lines: 0.6492,
            tasks: 257,
        },
    ),
    (
        "php",
        "python",
        VerbosityRatio {
            bytes: 0.9467,
            lines: 1.1268,
            tasks: 491,
        },
    ),
    (
        "php",
        "ruby",
        VerbosityRatio {
            bytes: 1.3996,
            lines: 1.4750,
            tasks: 475,
        },
    ),
    (
        "php",
        "rust",
        VerbosityRatio {
            bytes: 0.6232,
            lines: 0.6525,
            tasks: 448,
        },
    ),
    (
        "php",
        "scala",
        VerbosityRatio {
            bytes: 0.8229,
            lines: 1.2569,
            tasks: 444,
        },
    ),
    (
        "php",
        "shell",
        VerbosityRatio {
            bytes: 1.3333,
            lines: 1.2144,
            tasks: 251,
        },
    ),
    (
        "php",
        "sql",
        VerbosityRatio {
            bytes: 0.9241,
            lines: 1.2401,
            tasks: 65,
        },
    ),
    (
        "php",
        "swift",
        VerbosityRatio {
            bytes: 0.8644,
            lines: 0.9561,
            tasks: 322,
        },
    ),
    (
        "php",
        "typescript",
        VerbosityRatio {
            bytes: 0.8186,
            lines: 0.9035,
            tasks: 44,
        },
    ),
    (
        "php",
        "zig",
        VerbosityRatio {
            bytes: 0.3682,
            lines: 0.4807,
            tasks: 142,
        },
    ),
    (
        "python",
        "ruby",
        VerbosityRatio {
            bytes: 1.5754,
            lines: 1.5036,
            tasks: 1214,
        },
    ),
    (
        "python",
        "rust",
        VerbosityRatio {
            bytes: 0.6695,
            lines: 0.5961,
            tasks: 1192,
        },
    ),
    (
        "python",
        "scala",
        VerbosityRatio {
            bytes: 0.8760,
            lines: 1.0799,
            tasks: 938,
        },
    ),
    (
        "python",
        "shell",
        VerbosityRatio {
            bytes: 1.4029,
            lines: 1.0702,
            tasks: 363,
        },
    ),
    (
        "python",
        "sql",
        VerbosityRatio {
            bytes: 0.9327,
            lines: 0.9598,
            tasks: 88,
        },
    ),
    (
        "python",
        "swift",
        VerbosityRatio {
            bytes: 0.8366,
            lines: 0.7603,
            tasks: 640,
        },
    ),
    (
        "python",
        "typescript",
        VerbosityRatio {
            bytes: 0.9804,
            lines: 0.9590,
            tasks: 62,
        },
    ),
    (
        "python",
        "zig",
        VerbosityRatio {
            bytes: 0.4639,
            lines: 0.4821,
            tasks: 322,
        },
    ),
    (
        "ruby",
        "rust",
        VerbosityRatio {
            bytes: 0.4303,
            lines: 0.4046,
            tasks: 967,
        },
    ),
    (
        "ruby",
        "scala",
        VerbosityRatio {
            bytes: 0.5838,
            lines: 0.8142,
            tasks: 844,
        },
    ),
    (
        "ruby",
        "shell",
        VerbosityRatio {
            bytes: 0.9579,
            lines: 0.8172,
            tasks: 353,
        },
    ),
    (
        "ruby",
        "sql",
        VerbosityRatio {
            bytes: 0.6334,
            lines: 0.7355,
            tasks: 84,
        },
    ),
    (
        "ruby",
        "swift",
        VerbosityRatio {
            bytes: 0.5417,
            lines: 0.5373,
            tasks: 573,
        },
    ),
    (
        "ruby",
        "typescript",
        VerbosityRatio {
            bytes: 0.4801,
            lines: 0.4377,
            tasks: 55,
        },
    ),
    (
        "ruby",
        "zig",
        VerbosityRatio {
            bytes: 0.2886,
            lines: 0.3415,
            tasks: 223,
        },
    ),
    (
        "rust",
        "scala",
        VerbosityRatio {
            bytes: 1.2980,
            lines: 1.8371,
            tasks: 812,
        },
    ),
    (
        "rust",
        "shell",
        VerbosityRatio {
            bytes: 2.1648,
            lines: 1.8466,
            tasks: 334,
        },
    ),
    (
        "rust",
        "sql",
        VerbosityRatio {
            bytes: 1.3779,
            lines: 1.6520,
            tasks: 83,
        },
    ),
    (
        "rust",
        "swift",
        VerbosityRatio {
            bytes: 1.1762,
            lines: 1.2224,
            tasks: 592,
        },
    ),
    (
        "rust",
        "typescript",
        VerbosityRatio {
            bytes: 1.0449,
            lines: 1.1766,
            tasks: 58,
        },
    ),
    (
        "rust",
        "zig",
        VerbosityRatio {
            bytes: 0.6686,
            lines: 0.7964,
            tasks: 304,
        },
    ),
    (
        "scala",
        "shell",
        VerbosityRatio {
            bytes: 1.7033,
            lines: 1.0013,
            tasks: 331,
        },
    ),
    (
        "scala",
        "sql",
        VerbosityRatio {
            bytes: 0.9574,
            lines: 0.8177,
            tasks: 77,
        },
    ),
    (
        "scala",
        "swift",
        VerbosityRatio {
            bytes: 0.9209,
            lines: 0.6683,
            tasks: 513,
        },
    ),
    (
        "scala",
        "typescript",
        VerbosityRatio {
            bytes: 0.7871,
            lines: 0.6217,
            tasks: 51,
        },
    ),
    (
        "scala",
        "zig",
        VerbosityRatio {
            bytes: 0.5134,
            lines: 0.4268,
            tasks: 226,
        },
    ),
    (
        "shell",
        "sql",
        VerbosityRatio {
            bytes: 0.7190,
            lines: 1.0438,
            tasks: 51,
        },
    ),
    (
        "shell",
        "swift",
        VerbosityRatio {
            bytes: 0.6607,
            lines: 0.8348,
            tasks: 236,
        },
    ),
    (
        "shell",
        "zig",
        VerbosityRatio {
            bytes: 0.3479,
            lines: 0.5037,
            tasks: 108,
        },
    ),
    (
        "sql",
        "swift",
        VerbosityRatio {
            bytes: 0.9152,
            lines: 0.7913,
            tasks: 70,
        },
    ),
    (
        "sql",
        "zig",
        VerbosityRatio {
            bytes: 0.3959,
            lines: 0.3954,
            tasks: 29,
        },
    ),
    (
        "swift",
        "typescript",
        VerbosityRatio {
            bytes: 0.9113,
            lines: 0.9589,
            tasks: 45,
        },
    ),
    (
        "swift",
        "zig",
        VerbosityRatio {
            bytes: 0.5100,
            lines: 0.5723,
            tasks: 186,
        },
    ),
    (
        "typescript",
        "zig",
        VerbosityRatio {
            bytes: 0.7494,
            lines: 0.8271,
            tasks: 27,
        },
    ),
];

/// The verbosity of a language by profile ID, if the corpus covers it.
pub fn verbosity(language: &str) -> Option<&'static LanguageVerbosity> {
    VERBOSITY
        .binary_search_by_key(&language, |(id, _)| *id)
        .ok()
        .map(|index| &VERBOSITY[index].1)
}

/// The measured ratio of `left` to `right`, if the corpus covers both with
/// enough tasks in common.
pub fn verbosity_ratio(left: &str, right: &str) -> Option<VerbosityRatio> {
    if left == right {
        return None;
    }
    let (key, inverted) = if left < right {
        ((left, right), false)
    } else {
        ((right, left), true)
    };
    let found = RATIOS
        .binary_search_by_key(&key, |(left, right, _)| (*left, *right))
        .ok()
        .map(|index| RATIOS[index].2)?;
    Some(if inverted { found.inverted() } else { found })
}

/// Every measured pair, ordered and deduplicated: each pair appears once, with
/// the alphabetically first language on the left.
pub fn verbosity_ratios() -> impl Iterator<Item = (&'static str, &'static str, VerbosityRatio)> {
    RATIOS
        .iter()
        .map(|(left, right, ratio)| (*left, *right, *ratio))
}
